### ISSUE TITLE
Program doesn't work

### ISSUE THREAD

**Issue by jlnhlfan** [bartlomiejduda/EA-Graphics-Manager#5]
So, I saw what this program was allegedly capable of, and decided to try it out. However, from what I've seen, this claim:

Program for parsing FSH, SSH, XSH, PSH, GSH and MSH files from EA games.

is outright false. Allow me to explain.

I tried opening Mike Modano's portrait from NHL 09, which is 0566.ssh. It did not open.

I then opened an ssh file from NHL 2001. The program told me that preview for that file type is not supported, which is completely contradictory to this gif right here.
![image](https://github.com/bartlomiejduda/EA-Graphics-Manager/assets/31529087/cc171ef2-5015-446b-848f-851c838ad025)

I then opened Greg Adams' headshot from NHL 2001 on the PS1, which is a .psh file. The same message appeared.

This program doesn't do what it claims to do, and GitHub should do something about the false claims.

Please actually support these file types so that what you see on the main page is actually what you get.

**Comment by bartlomiejduda** [comment]
I think you are confusing the concepts. Parsing file is something else than previewing images or even exporting and importing image data. Parsing function works perfectly fine on almost all image types mentioned on Xentax Wiki.

Currently version 0.14.3 supports preview for image types 2, 4, 66 and 125 ONLY.
And that's EXACTLY what you can see on the included GIF in the readme file. :)
So there are no false claims there.

If you want support for other image types, you have to at least include some samples and ask nicely for support.
If you won't attach samples, I will just close this issue.

**Comment by jlnhlfan** [comment]
Sorry about that. I'll gather some samples to send.

**Comment by jlnhlfan** [comment]
[samples.zip](https://github.com/bartlomiejduda/EA-Graphics-Manager/files/12188920/samples.zip)
Here are some samples of these kinds of files, separated into folders that indicate which types they are.

**Comment by jlnhlfan** [comment]
Have you tested the samples yet?

**Comment by bartlomiejduda** [comment]
Hi, yes, your samples from directories "PSH" and "SSH (NHL 2001 to 2003)" are partially supported in version **v0.15.2** (image preview only).

Samples from directory "SSH (NHL 2005 to 09)" are not supported yet

**Comment by jlnhlfan** [comment]
Alright. Here's the thing: I have only seen that version as a commit, and coding isn't really my thing.

**Comment by bartlomiejduda** [comment]
Ok, so please wait until new version will be compiled and released by me.
You can subscribe to this repository to get e-mail notifications when it comes out.

**Comment by jlnhlfan** [comment]
Alright, will do. I apologize for my misunderstanding.

**Comment by bartlomiejduda** [comment]
@jlnhlfan I've just published new version of the program https://github.com/bartlomiejduda/EA-Graphics-Manager/releases/tag/v0.15.6
