### ISSUE TITLE
Question about opening/editing SSH files (MVP Baseball 07 - NCAA Baseball)

### ISSUE THREAD

**Issue by ZMO34** [bartlomiejduda/EA-Graphics-Manager#6]
Hey man I'm ZMO, a modder for MVP07 Reborn, a mod for MVP 07

We have been able to use PCSX2 texture replacements to use 4k resolution textures inside the game, but we have not been able to edit the files from the PS2 game.  Do you have any advice, or could you help with getting into those files?
Thanks for your time

-The Reborn Modding team
discord.gg/rebornsports

**Comment by bartlomiejduda** [comment]
Hi. MVP Baseball 07 uses image types 1, 2, 5 and 14.

As for image types 1/2/5 they are supported for preview and export only by EA Graphics Manager.
Image type 14 is not supported at all.

I heard that some people do the texture replacement manually by using Console Texture Explorer and Game Graphic Studio, so you can try that method as well.

**Comment by bartlomiejduda** [comment]
@ZMO34 FYI, image type 14 is now supported for preview/export in **v0.19.8** release of EA Graphics Manager.
