### ISSUE TITLE
GSH/FSH from Madden NFL 13 (Wii) not previewing correctly

### ISSUE THREAD

**Issue by WiiExpertise** [bartlomiejduda/EA-Graphics-Manager#7]
Thanks for the awesome work with this program. I can tell a lot of progress has been made over time.

I have been trying to preview/extract FSH and GSH images from Madden NFL 13 (Wii), and while the most recently built release version is able to open them, it does not appear to be reading the image correctly, as shown with a couple examples:
![image](https://github.com/user-attachments/assets/cd226ddb-9e57-486d-bc6f-d62c03c01354)
![image](https://github.com/user-attachments/assets/6afc1c93-9846-4805-a166-5087a503b0dd)
![image](https://github.com/user-attachments/assets/112517b7-d6a2-4541-8490-5a56ccde0c78)

I believe it uses the 0x1E image format.

Here is a zip with a few sample fsh and gsh files:
[samplefshandgsh.zip](https://github.com/user-attachments/files/18249504/samplefshandgsh.zip)

Thanks!

**Comment by bartlomiejduda** [comment]
Ah yes, it was fixed already in the newer version (**v0.23.5**).
![obraz](https://github.com/user-attachments/assets/048f4947-78bc-44fd-a25a-c9ec6bbd2b80)

Try to build from source the newest version. Instruction is in readme file on github.
https://github.com/bartlomiejduda/EA-Graphics-Manager?tab=readme-ov-file#building-on-windows
Or you can just wait for the new release which should happen soon.
